/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamientosRouteImport } from './routes/tratamientos'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TratamientosIndexRouteImport } from './routes/tratamientos.index'
import { Route as ProductosIndexRouteImport } from './routes/productos.index'
import { Route as TratamientosSlugRouteImport } from './routes/tratamientos.$slug'
import { Route as ProductosCategoriaRouteImport } from './routes/productos.$categoria'

const TratamientosRoute = TratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosIndexRoute = TratamientosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TratamientosRoute,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamientosSlugRoute = TratamientosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TratamientosRoute,
} as any)
const ProductosCategoriaRoute = ProductosCategoriaRouteImport.update({
  id: '/productos/$categoria',
  path: '/productos/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/instagram': typeof InstagramRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tratamientos': typeof TratamientosRouteWithChildren
  '/productos/$categoria': typeof ProductosCategoriaRoute
  '/tratamientos/$slug': typeof TratamientosSlugRoute
  '/productos/': typeof ProductosIndexRoute
  '/tratamientos/': typeof TratamientosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/instagram': typeof InstagramRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/productos/$categoria': typeof ProductosCategoriaRoute
  '/tratamientos/$slug': typeof TratamientosSlugRoute
  '/productos': typeof ProductosIndexRoute
  '/tratamientos': typeof TratamientosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/instagram': typeof InstagramRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/tratamientos': typeof TratamientosRouteWithChildren
  '/productos/$categoria': typeof ProductosCategoriaRoute
  '/tratamientos/$slug': typeof TratamientosSlugRoute
  '/productos/': typeof ProductosIndexRoute
  '/tratamientos/': typeof TratamientosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/instagram'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/tratamientos'
    | '/productos/$categoria'
    | '/tratamientos/$slug'
    | '/productos/'
    | '/tratamientos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/instagram'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/productos/$categoria'
    | '/tratamientos/$slug'
    | '/productos'
    | '/tratamientos'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/instagram'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/servicios'
    | '/sobre-nosotros'
    | '/tratamientos'
    | '/productos/$categoria'
    | '/tratamientos/$slug'
    | '/productos/'
    | '/tratamientos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  InstagramRoute: typeof InstagramRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  TratamientosRoute: typeof TratamientosRouteWithChildren
  ProductosCategoriaRoute: typeof ProductosCategoriaRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamientos': {
      id: '/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof TratamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientos/': {
      id: '/tratamientos/'
      path: '/'
      fullPath: '/tratamientos/'
      preLoaderRoute: typeof TratamientosIndexRouteImport
      parentRoute: typeof TratamientosRoute
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamientos/$slug': {
      id: '/tratamientos/$slug'
      path: '/$slug'
      fullPath: '/tratamientos/$slug'
      preLoaderRoute: typeof TratamientosSlugRouteImport
      parentRoute: typeof TratamientosRoute
    }
    '/productos/$categoria': {
      id: '/productos/$categoria'
      path: '/productos/$categoria'
      fullPath: '/productos/$categoria'
      preLoaderRoute: typeof ProductosCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TratamientosRouteChildren {
  TratamientosSlugRoute: typeof TratamientosSlugRoute
  TratamientosIndexRoute: typeof TratamientosIndexRoute
}

const TratamientosRouteChildren: TratamientosRouteChildren = {
  TratamientosSlugRoute: TratamientosSlugRoute,
  TratamientosIndexRoute: TratamientosIndexRoute,
}

const TratamientosRouteWithChildren = TratamientosRoute._addFileChildren(
  TratamientosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  InstagramRoute: InstagramRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  ServiciosRoute: ServiciosRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  TratamientosRoute: TratamientosRouteWithChildren,
  ProductosCategoriaRoute: ProductosCategoriaRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
